services:
  - type: web_service
    name: 1111-app
    env: docker
    region: oregon
    branch: main
    root: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: https://1111-app.onrender.com
      APP_KEY: ''
      DB_CONNECTION: pgsql
      DB_HOST: ''
      DB_PORT: '5432'
      DB_DATABASE: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      NUXT_PUBLIC_API_BASE: https://1111-app.onrender.com
      NODE_ENV: production
